name: Deploy StorageApp Frontend

on:
    push: 
        branches: 
            - main
            # - deploy

jobs:
    deploy-frontend:
        runs-on: ubuntu-latest
        env:
          S3_BUCKET_NAME: storage-app-frontend
          CLOUDFRONT_DISTRIBUTION_ID: E35JPYRACDTD7Z
          VITE_BACKEND_BASE_URL: https://api.mirhaadi.in
          VITE_RAZORPAY_KEY_ID: rzp_live_T7QqY1ykKdipTT
          VITE_GOOGLE_CLIENT_ID: 594555697613-18p3s2o6hl7mvc3gj0o2a2bg7b27tj9m.apps.googleusercontent.com

        steps:
          - name: Clone frontend repository
            uses: actions/checkout@v4
            
          - name: Setup Node
            uses: actions/setup-node@v4

          - name: Install dependencies
            run: npm ci

          - name: Run tests
            run: npm run test

          - name: Build app
            run: npm run build

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Upload to S3
            run: aws s3 sync dist/ "s3://${S3_BUCKET_NAME}/" --delete

          - name: Invalidate CloudFront
            run: |
              aws cloudfront create-invalidation \
                --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
                --paths "/index.html"

          - name: Deployment complete
            run: echo "Frontend Deployed Successfully..."